##---
# Source: catalog/templates/migration-job.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: migration-job-account
  namespace: default
  labels:
    migration-job: "true"
    app: service-catalog-catalog-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: migration-job-account
  labels:
    migration-job: "true"
    app: service-catalog-catalog-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:     ["get", "update"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs:     ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs:     ["delete"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterserviceclasses"
    - "clusterserviceplans"
    - "clusterservicebrokers"
    - "serviceinstances"
    - "servicebindings"
    - "serviceclasses"
    - "serviceplans"
    - "servicebrokers"
    verbs: ["list", "get", "create", "patch", "delete"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterservicebrokers/status"
    - "clusterserviceclasses/status"
    - "clusterserviceplans/status"
    - "serviceinstances/status"
    - "serviceinstances"
    - "servicebindings/status"
    - "servicebrokers/status"
    - "serviceclasses/status"
    - "serviceplans/status"
    verbs: ["update"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: migration-job-account
  labels:
    migration-job: "true"
    app: service-catalog-catalog-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: migration-job-account
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: migration-job-account

---
apiVersion: batch/v1
kind: Job
metadata:
  name: service-catalog-catalog-migration-job
  labels:
    app: service-catalog-catalog-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 140
  template:
    metadata:
      labels:
        migration-job: "true"
        app: service-catalog-catalog-migration-job
        chart: "catalog-0.3.0-beta.2"
        release: "service-catalog"
        heritage: "Tiller"
    spec:
      restartPolicy: Never
      serviceAccountName: migration-job-account
      imagePullSecrets:
        []
        
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: service-catalog-catalog-migration-storage
      containers:
        - name: job
          image: quay.io/kubernetes-service-catalog/service-catalog:v0.3.0-beta.2
          imagePullPolicy: Always
          args:
          - migration
          - --action
          - restore
          - --service-catalog-namespace
          - default
          - --controller-manager-deployment
          - service-catalog-catalog-controller-manager
          - --storage-path=data/
          - --webhook-service-name
          - service-catalog-catalog-webhook
          - --webhook-service-port
          - "443"
          - --pvc-name
          - service-catalog-catalog-migration-storage
          volumeMounts:
          - name: storage
            mountPath: /data
