##---
# Source: catalog/templates/pre-migration-job.yaml
kind: ServiceAccount
apiVersion: v1
metadata:
  name: pre-migration-job-account
  namespace: default
  labels:
    migration-job: "true"
    app: service-catalog-catalog-pre-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-migration-job-account
  labels:
    migration-job: "true"
    app: service-catalog-catalog-pre-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs:     ["get", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs:     ["get", "update"]
  - apiGroups: ["servicecatalog.k8s.io"]
    resources:
    - "clusterserviceclasses"
    - "clusterserviceplans"
    - "clusterservicebrokers"
    - "serviceinstances"
    - "servicebindings"
    - "serviceclasses"
    - "serviceplans"
    - "servicebrokers"
    verbs: ["get", "list", "delete", "update"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources: ["validatingwebhookconfigurations"]
    verbs: ["create", "delete"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: pre-migration-job-account
  labels:
    migration-job: "true"
    app: service-catalog-catalog-pre-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
subjects:
  - kind: ServiceAccount
    name: pre-migration-job-account
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pre-migration-job-account

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: service-catalog-catalog-migration-storage
  labels:
    migration-job: "true"
    app: service-catalog-catalog-pre-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi

---
apiVersion: batch/v1
kind: Job
metadata:
  name: service-catalog-catalog-pre-migration-job
  labels:
    migration-job: "true"
    app: service-catalog-catalog-pre-migration-job
    chart: "catalog-0.3.0-beta.2"
    release: "service-catalog"
    heritage: "Tiller"
  annotations:
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  backoffLimit: 1
  activeDeadlineSeconds: 120
  template:
    metadata:
      labels:
        migration-job: "true"
        app: service-catalog-catalog-pre-migration-job
        chart: "catalog-0.3.0-beta.2"
        release: "service-catalog"
        heritage: "Tiller"
    spec:
      restartPolicy: Never
      serviceAccountName: pre-migration-job-account
      imagePullSecrets:
        []
        
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: service-catalog-catalog-migration-storage
      containers:
        - name: job
          image: quay.io/kubernetes-service-catalog/service-catalog:v0.3.0-beta.2
          imagePullPolicy: Always
          args:
          - migration
          - --action
          - backup
          - --service-catalog-namespace
          - default
          - --controller-manager-deployment
          - service-catalog-catalog-controller-manager
          - --apiserver-deployment
          - service-catalog-catalog-apiserver
          - --storage-path=data/
          volumeMounts:
          - name: storage
            mountPath: /data
